DROP TABLE IF EXISTS RAILWAY CASCADE;
DROP TABLE IF EXISTS STATION;
DROP SEQUENCE IF EXISTS SEQ_RAILWAY;
DROP SEQUENCE IF EXISTS SEQ_STATION;

CREATE SEQUENCE SEQ_RAILWAY START 100000;
CREATE SEQUENCE SEQ_STATION START 100000;

CREATE TABLE RAILWAY
(
  RW_ID         INTEGER PRIMARY KEY DEFAULT nextval('SEQ_RAILWAY'),
  RW_NAME       VARCHAR,
  RW_SHORTNAME  VARCHAR
);

CREATE TABLE STATION (
  ST_ID         INTEGER PRIMARY KEY DEFAULT nextval('SEQ_STATION'),
  ST_NAME       VARCHAR,
  ST_RWID       INTEGER NOT NULL,
  ST_CODE       VARCHAR,
  ST_ACTIVE     INTEGER,
  ST_CODERW     VARCHAR,
  FOREIGN KEY (ST_RWID) REFERENCES RAILWAY (RW_ID) ON DELETE CASCADE
);
