DELETE FROM RAILWAY;
ALTER SEQUENCE SEQ_RAILWAY RESTART WITH 100000;
ALTER SEQUENCE SEQ_STATION RESTART WITH 100000;

-- first
INSERT INTO RAILWAY (RW_NAME, RW_SHORTNAME)
VALUES ('first way', 'fw');
-- second
INSERT INTO RAILWAY (RW_NAME, RW_SHORTNAME)
VALUES ('second way', 'sw');

INSERT INTO STATION (ST_NAME, ST_CODE, ST_ACTIVE, ST_CODERW, ST_RWID) VALUES ('samara', '0001', 1, 'x1', 100000);
INSERT INTO STATION (ST_NAME, ST_CODE, ST_ACTIVE, ST_CODERW, ST_RWID) VALUES ('moscow', '0002', 2, 'x2', 100000);
INSERT INTO STATION (ST_NAME, ST_CODE, ST_ACTIVE, ST_CODERW, ST_RWID) VALUES ('turin', '1001', 1, 'z1', 100001);
INSERT INTO STATION (ST_NAME, ST_CODE, ST_ACTIVE, ST_CODERW, ST_RWID) VALUES ('praha', '1002', 1, 'z1', 100001);
